<script type="text/javascript" src="js/FixMultiSelectionModel.js"></script>
<script type="text/javascript" src="js/managers.js"></script>
<script language="javascript">
var Localize = {
    Save: '<%@ Save %>',
    Create: '<%@ Create %>',
    Edit: '<%@ Edit %>',
    Remove: '<%@ Remove %>',
    Add: '<%@ Add %>',
    AllAvailable: '<%@ All available %>',
    Assigned: '<%@ Assigned %>',
    Free: '<%@ Free %>',
    UGRead: '<%@ Users groups granted to read %>',
    UGWrite: '<%@ Users groups granted to modify %>',
    Login: '<%@ Login %>',
    ExternalPaySystem: '<%@ External pay-system %>',
    UseAdvance: '<%@ Use advance payments %>',
    Office: '<%@ Office %>',
    Description: '<%@ Description %>',
    Password: '<%@ Password %>',
    HideUserPass: '<%@ Hide %> <%@ users passwords %>',
    ShowPasswords: '<%@ Show %> <%@ passwords %>',
    Manager: '<%@ Manager %>',
    Managers: '<%@ Managers %>',
    PersonFullName: '<%@ Person full name %>',
    Quant: '<%@ Quant. %>',
    ReadOnly: '<%@ Read only %>',
    ReadWrite: '<%@ Read and write %>',
    BackList: '<%@ Go back to list %>',
    Connecting: '<%@ Connecting %>',
    SendingData: '<%@ Sending data %>',
    TariffsToRead: '<%@ Tariffs granted to read %>',
    TariffsToModify: '<%@ Tariffs granted to modify %>',
    UsrsGrps: '<%@ Users groups %>',
    PersonFullName: '<%@ Person full name %>',
    Description: '<%@ Description %>',
    Balance: '<%@ Balance %>',
    Symbol: '<%@ Symbol %>',
    Agreement: '<%@ Agreement %>',
    Address: '<%@ Address %>',
    Phone: '<%@ Phone %>',
    Login: '<%@ Login %>',
    UserLogin: '<%@ User login %>',
    AccountLogin: '<%@ Account login %>',
    Search: '<%@ Search %>',
    UserTpl: '<%@ User template %>',
    Template: '<%@ Template %>',
    EditUser: '<%@ Edit user %>',
    Remove: '<%@ Remove %>',
    UserType: '<%@ User type %>',
    Legal: '<%@ Legal person %>',
    Physic: '<%@ Physical person %>',
    SendingData: '<%@ Sending data %>',
    Connecting: '<%@ Connecting %>',
    AUsrFrmFields: '<%@ Additional user form fields %>',
    Type: '<%@ Type %>',
    DeleteField: '<%@ Remove %> <%@ field %>',
    EditField: '<%@ Edit %> <%@ field %>',
    Error: '<%@ Error %>',
    AddNewRecord: '<%@ Add new record %>',
    Cancel: '<%@ Cancel %>',
    Save: '<%@ Save %>',
    AddValue: '<%@ Add %> <%@ value %>',
    Value: '<%@ Value %>',
    DefinedValues: '<%@ Defined values %>',
    Field: '<%@ Field %>',
    Text: '<%@ Text %>',
    List: '<%@ List %>',
    Logic: '<%@ Logic %>',
    AND: '<%@ AND %>',
    OR: '<%@ OR %>',
    Date: '<%@ Date %>',
    equal: '<%@ equal %>',
    notequal: '<%@ not %> <%@ equal %>',
    equalmorethan: '<%@ equal %> <%@ or %> <%@ more than %>',
    equallessthan: '<%@ equal %> <%@ or %> <%@ less than %>',
    morethan: '<%@ more than %>',
    lessthan: '<%@ less than %>',
    contains: '<%@ contains %>',
    Condition: '<%@ Condition %>',
    Blocking: '<%@ Blocking %>',
    Blocked: '<%@ Blocked %>',
    ByClient: '<%@ by client %>',
    ByMan: '<%@ by manager %>',
    ByBalance: '<%@ by balance %>',
    ByTraf: '<%@ by traffic %>',
    Paycode: '<%@ Paycode %>',
    Module: '<%@ Agent %>',
    Tarif: '<%@ Tarif %>',
    SearchTemplate: '<%@ Search template %>',
    Name: '<%@ Name %>',
    Property: '<%@ Property %>',
    AddNewCondition: '<%@ Add %> <%@ new condition %>',
    Change: '<%@ Change %>',
    AdvancedSearch: '<%@ Advanced search %>',
    rules: '<%@ rules %>',
    Create: '<%@ Create %>',
    Apply: '<%@ Apply %>',
    CurrentShape: '<%@ Current shape %>',
    Credit: '<%@ Credit %>',
    UserName: '<%@ User name %>',
    FilterRecords: '<%@ Filter of records %>',
    All: '<%@ All %>',
    Users: '<%@ Users %>',
    Operator: '<%@ Operator %>',
    Dealer: '<%@ Dealer %>',
    AccessRestricted: '<%@ Access is restricted to this section %>',
    Payments: '<%@ Payments %>',
    Undefined: '<%@ Undefined %>',
    Subscriber: '<%@ Subscriber %>',
    Info: '<%@ Info %>',
    RequestDone: '<%@ Request done successfully %>',
    LegalOwner: '<%@ LegalOwner %>',
    Agent: '<%@ Agent %>',
    Advertiser: '<%@ Advertiser %>',
    Partner: '<%@ Partner %>',
    LegalAddress: '<%@ Legal address %>',
    RegisteredAddress: '<%@ Registered address %>',
    AddressDeliverInvoice: '<%@ Address to deliver invoice %>',
    PostAddress: '<%@ Post address %>',
    PromisedPayment: '<%@ Promised payment %>',
    Category: '<%@ Category %>',
    UndefNumber: '<%@ Agreement number %> <%@ undefined %>',
    SavePayment: '<%@ Save payment %>',
    BalanceHistory: '<%@ Balance history %>',
    CurBalance: '<%@ Current Balance %>',
    SetBalance: '<%@ Set balance value %>',
    PaymentSum: '<%@ Payment sum%>',
    PaymentDate: '<%@ Payment date %>',
    PaymentsHistory: '<%@ Show payments history %>',
    Currency: '<%@ Currency %>',
    Comment: '<%@ Comment %>',
    Default: '<%@ Default %>',
    Payment: '<%@ Payment %>',
    user: '<%@ user %>',
    agreement: '<%@ agreement %>',
    Warning: '<%@ Warning %>',
    Info: '<%@ Info %>',
    RequestSuccessfully: '<%@ Request done successfully %>',
    DateOffSebt: '<%@ Date to pay off debt %>',
    MaxPayment: '<%@ Maximum %> <%@ payment %>',
    MinPayment: '<%@ Minimum %> <%@ payment %>',
    AllowedDebt: '<%@ Allowed debt %>',
    PaymentDoesNotDebt: '<%@ This payment does not write off debt %>',
    PromisedExists: '<%@ There is promised payment for this agreement %>',
    PromisedInCredit: '<%@ Attantion! There was promised payment %>',
    PaymentNumber: '<%@ Pay document number %>',
    Since: '<%@ Since %>',
    Till: '<%@ Till %>',
    HideEmptyCharges: '<%@ Hide empty charges %>',
    RentCharges: '<%@ Rent charges %>',
    Amount: '<%@ Amount %>',
    User: '<%@ User %>',
    Locks: '<%@ Locks %>',
    LockSet: '<%@ Lock set %>',
    LockRemoved: '<%@ Lock removed %>',
    LockType: '<%@ Lock type %>',
    TurnedOff: '<%@ Turned off %>',
    Blocked: '<%@ Blocked %>',
    bytraffic: '<%@ by traffic %>',
    bybalance: '<%@ by balance %>',
    bymanager: '<%@ by manager %>',
    byclient: '<%@ by client %>',
    SelectAllAndRemove: '<%@ Select all %> <%@ and %> <%@ remove %>',
    RemoveSelected: '<%@ Remove selected %>',
    Collapse: '<%@ Collapse %>',
    Expand: '<%@ Expand %>',
    AllAvailable: '<%@ All available %> <%@ users %>',
    Reason: '<%@ Reason %>',
    Show: '<%@ Show %>',
    Hide: '<%@ Hide %>',
    agreements: '<%@ agreements %>',
    ShowAInfo: '<%@ Show additional information %>',
    HideAInfo: '<%@ Hide additional information %>',
    LockManagement: '<%@ Lock management %>',
    LockAllAccounts: '<%@ Lock all accounts %>',
    UnlockAllAccounts: '<%@ Unlock all accounts %>',
    CreateUserByTemplate: '<%@ Create user using template %>'
};
</script>
<table class="table_comm" width="730" align="center" style="border-top: none; background: none;"><tr><td id="menPanelPlace"></td></tr></table>