<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Agreement balance' => '',
  'Agreement number' => '',
  'Available balance' => '',
  'Common info' => '',
  'Cost' => '',
  'Current turbo services' => '',
  'Description' => '',
  'Duration' => '',
  'End date' => '',
  'Error' => '',
  'Error!' => '',
  'Length of service' => '',
  'License Agreement' => '',
  'Login' => '',
  'Next' => '',
  'Not enough balance' => '',
  'Pay' => '',
  'Purchase' => '',
  'Return to the main page' => '',
  'Return to the previous page' => '',
  'Return to the start page' => '',
  'Select account' => '',
  'Select service' => '',
  'Selecting duration' => '',
  'Selecting service' => '',
  'Selecting vgroup' => '',
  'Service' => '',
  'Services' => '',
  'Shape' => '',
  'Sorry, error is here. Click link below to return to the main page.' => '',
  'Sorry, error is here. You need to accept License Agreements first.' => '',
  'Start' => '',
  'Start date' => '',
  'TURBO-internet' => '',
  'TURBO-internet successfully purchased!' => '',
  'Terms' => '',
  'There is no available accounts' => '',
  'There is no available services' => '',
  'Total cost' => '',
  'Turbo' => '',
  'Turbo terms and conditions' => '',
  'User account' => '',
  'You have select the following service parameters:' => '',
  'save' => '',
  '{n} hour|{n} hours' => '',
  '{totalBalance} (Agreement balance: {balance}; credit: {credit})' => '',
  'Заказать' => '',
  'Ошибка сохранения данных!' => '',
  'условия' => '',
);
