<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'By clicking Start, you agree to the terms stated in the License Agreement above.' => 'Нажимая на кнопку Начать, вы соглашаетесь с указанными выше условиями лицензионного соглашения',
  'Sorry, error is here. You need to accept License Agreements first.' => 'Для заказа услуги необходимо принять условия лицензионного соглашения.',
  'TURBO-internet successfully purchased!' => 'Услуга TURBO-интернет успешно заказана!',
  'There is no available accounts' => 'Нет доступных учетных записей',
  'There is no available services' => 'Нет доступных услуг',
  'save' => 'Сохранить',
  'Заказать' => 'Заказать',
  'Ошибка сохранения данных!' => '',
  'условия' => '',
  'Agreement balance' => 'Баланс договора',
  'Agreement number' => 'Номер договора',
  'Available balance' => 'Доступный баланс',
  'Common info' => 'Оплата услуги',
  'Cost' => 'Стоимость',
  'Current turbo services' => 'Действующие услуги TURBO-интернет',
  'Description' => 'Описание',
  'Duration' => 'Длительность',
  'End date' => 'Дата окончания',
  'Error' => 'Ошибка',
  'Error!' => 'Ошибка!',
  'Length of service' => 'Время действия услуги (часов)',
  'License Agreement' => 'Условия использования',
  'Login' => 'Логин',
  'Next' => 'Продолжить',
  'Not enough balance' => 'Не достаточен баланс для заказа услуги',
  'Pay' => 'Оплатить',
  'Purchase' => 'Заказать',
  'Return to the main page' => 'Вернуться на главную страницу',
  'Return to the previous page' => 'Вернуться на предыдущую страницу',
  'Return to the start page' => 'Вернуться на начальную страницу',
  'Select account' => 'Выберите аккаунт',
  'Select service' => 'Выберите услугу',
  'Selecting duration' => 'Выбор продолжительности',
  'Selecting service' => 'Выбор услуги',
  'Selecting vgroup' => 'Выбор аккаунта',
  'Service' => 'Услуга',
  'Services' => 'Услуги',
  'Shape' => 'Скорость',
  'Sorry, error is here. Click link below to return to the main page.' => 'Извините, произошла ошибка. Нажмите ссылку ниже, что бы вернуться в начало.',
  'Start' => 'Начать',
  'Start date' => 'Дата начала',
  'TURBO-internet' => 'TURBO-интернет',
  'Terms' => 'Условия использования',
  'Total cost' => 'Итоговая стоимость',
  'Turbo' => 'TURBO',
  'Turbo terms and conditions' => 'Условия использования',
  'User account' => 'Аккаунт пользователя',
  'You have select the following service parameters:' => 'Параметры заказа:',
  '{n} hour|{n} hours' => '{n} час|{n} часа|{n} часов|{n} часа',
  '{totalBalance} (Agreement balance: {balance}; credit: {credit})' => '{totalBalance} (Баланс договора: {balance}; Кредит: {credit})',
);
